kind: pipeline
type: docker
name: default

steps:
  - name: install-dependencies
    image: node:20
    commands:
      - npm install

  - name: build
    image: node:20
    commands:
      - npm run build

  - name: deploy
    image: ubuntu:20.04
    environment:
      SSH_PRIVATE_KEY:
        from_secret: ssh_private_key
      REMOTE_SERVER:
        from_secret: remote_server
      REMOTE_USER:
        from_secret: remote_user
      DEPLOY_PATH:
        from_secret: deploy_path
    commands:
      - apt-get update && apt-get install -y rsync openssh-client
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H $REMOTE_SERVER >> ~/.ssh/known_hosts
      - ls -lsa
      - rsync -avz -e "ssh -i ~/.ssh/id_rsa" dist/ $REMOTE_USER@$REMOTE_SERVER:$DEPLOY_PATH

trigger:
  branch:
    - main
